// Generated by https://quicktype.io

namespace MedicoverBot
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class FilterDatas
    {
        [JsonProperty("services")]
        public Entry[] Services { get; set; }

        [JsonProperty("clinics")]
        public Entry[] Clinics { get; set; }

        [JsonProperty("doctors")]
        public List<Entry> Doctors { get; set; }

        [JsonProperty("doctorLanguages")]
        public Entry[] DoctorLanguages { get; set; }
    }

    public partial class Entry
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }
    }

}